autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - Tritium-VLK/balancer-v2-monorepo@2023.04.24

compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
          - "@balancer=Tritium-VLK/balancer-v2-monorepo@2023.04.24"
